name: FTop
main: com.zeshanaslam.ftop.Main
version: 1.4.0
depend: [HolographicDisplays, Factions, Vault, Citizens, Essentials, ProtocolLib]
softdepend: [MobArena, KoTH, HealthBar, PlaceholderAPI, SilkSpawners, SupplyDrop]